### ISSUE TITLE
Rainmeter trigger not working perfectly

### ISSUE THREAD

**Issue by EricMuhren** [jtebbens/com.homewizard#15]
The rainmeter trigger now and then fires suddenly. This morning the value of rain was 1,4 mm. Then it stopped raining. The whole day now and then the rainflow was triggered. In the beginning it looked like it was triggered every half hour. Later on it stopped and a few hours later it started triggering again. The value of the rainmeter is still 1,4 mm. It's not stable.

I implemented another version using the value "rainfall today" and I store it every 5 minutes in a variable. Then I trigger a flow when the value changes. This works perfect. But I like the rain trigger to work as well. That's better....and then I only need one flow.

P.s. Perhaps you have to try this:
rain_daytotal <= devices[device_id].last_raintotal instead of using !=

**Comment by jtebbens** [comment]
Hi Eric,

Sorry to hear it is still not stable. It is hard for me to troubleshoot because I do not own a rainmeter or weather station. 
My only guess for now around this problem is that I am receiving an Undef value in between some of these polls (communitcation problem with Homewizard as you have noticed in your script). What I can do is add is another undef check to be ignored at the equation.

Kind regards / Groet,
Jeroen

Op 13 sep. 2019 om 19:47 heeft EricMuhren <notifications@github.com <mailto:notifications@github.com> > het volgende geschreven:

The rainmeter trigger now and then fires suddenly. This morning the value of rain was 1,4 mm. Then it stopped raining. The whole day now and then the rainflow was triggered. In the beginning it looked like it was triggered every half hour. Later on it stopped and a few hours later it started triggering again. The value of the rainmeter is still 1,4 mm. It's not stable.

I implemented another version using the value "rainfall today" and I store it every 5 minutes in a variable. Then I trigger a flow when the value changes. This works perfect. But I like the rain trigger to work as well. That's better....and then I only need one flow.

**Comment by EricMuhren** [comment]
Yes that could be the problem too. I also think it has something to do with an undef or null or 0. And using  != when you know it must always be <= is also a better solution.

I only want to help you to get this working by providing as much information as I can.

**Comment by jtebbens** [comment]
Hi Eric, I pushed a code change to beta branch (Git). I also sent it to Homey for approval. When done I will release it in the beta channel so you can install it.

**Comment by EricMuhren** [comment]
Thanks a lot Jeroen!

**Comment by jtebbens** [comment]
Hi Eric, app is in the beta channel now. Please try to see if the trigger works better.

**Comment by EricMuhren** [comment]
Hi Jeroen,

I’m not able to install the beta version. It doesn’t appear on the web page.

**Comment by jtebbens** [comment]
Sorry forgot to publish. It’s pushed to stable now even. Running it myself without a problem.

Op 20 sep. 2019 om 20:27 heeft EricMuhren <notifications@github.com <mailto:notifications@github.com> > het volgende geschreven:

Hi Jeroen,

I’m not able to install the beta version. It doesn’t appear on the web page.

**Comment by EricMuhren** [comment]
Hi Jeroen,

Rainmeter seems to work fine now. Thanks!

**Comment by jtebbens** [comment]
Thanks for the confirmation! Will close the issue.
