### ISSUE TITLE
Can't connect my HomeWizard to my Homey Pro

### ISSUE THREAD

**Issue by mtvdham** [jtebbens/com.homewizard#44]
I have installed the Homewizard app on my homey everting looks good. Only when i like to connect i fill in the local ip adress en the key then nothing happen?! Can you tel me what i have done wrong?

**Comment by jtebbens** [comment]
Either your HomeWizard ip is wrong or password.

Verify in browser if this works.

http://x.x.x.x/password/get-sensors

**Comment by PaulLoos** [comment]
I have the same problem. Installed a Homey-Pro and want to connect my Homewizard to Homey. 1st rebooted both, then installed the Homewizard-app in Homey (no problems) then try to add the HW as device. At the IP address I add: 192.168.0.5:82 (port 82) and then the local password of HW.  But then, nothing happens because the "opslaan" button does not respond. Homey is in the same network. (192.168.0.121) . Both HW and Homey run fine seperately. What can I try more? Thanks!

**Comment by jtebbens** [comment]
> 
> 
> I have the same problem. Installed a Homey-Pro and want to connect my Homewizard to Homey. 1st rebooted both, then installed the Homewizard-app in Homey (no problems) then try to add the HW as device. At the IP address I add: 192.168.0.5:82 (port 82) and then the local password of HW. But then, nothing happens because the "opslaan" button does not respond. Homey is in the same network. (192.168.0.121) . Both HW and Homey run fine seperately. What can I try more? Thanks!

Answer to that is simple. The code does not cater for port 82 but expects the default 80 for homewizard

**Comment by PaulLoos** [comment]
Thank you for your answer.
Allthough I have tried this, without succes, i will try this option again in the next days and let you know.

23 apr. 2021 17:25:34 jtebbens ***@***.***>:

**Comment by mtvdham** [comment]
To day it’s work by me to connect the HomeWizard

**Comment by jtebbens** [comment]
Closed issue (default port is 80/tcp)

**Comment by PaulLoos** [comment]
Problem solved this afternoon.
Although the settings within HW showed 192.168.0.5 , the real IP was an
other.
Since an other device had 192.168.0.5, a ping confirmed that there was
indeed a device.

So, after completely resetting the HW, and set a new IP number, your app
found it and installed it in Homey.

Thank you for your support!

Op wo 28 apr. 2021 om 14:58 schreef jtebbens ***@***.***>:
